### ISSUE TITLE
oh-my-zsh compatibility

### ISSUE THREAD

**Issue by jtmkrueger** [iam4x/zsh-iterm-touchbar#1]
Is there a way to install this with oh-my-zsh? If so, can you add it to the readme? If not, any plans to add compatibility?

**Comment by jtmkrueger** [comment]
I tried cloning and adding `source ~/.zsh/zsh-iterm-touchbar/zsh-iterm-touchbar.plugin.zsh` to my `.zshrc` but I don't think it's working. Is there anything else I should need to do?

**Comment by iam4x** [comment]
Can you try to and give me the results?

Clone the repo in your plugins directory:

* `$ cd ${ZSH_CUSTOM1:-$ZSH/custom}/plugins`
* `$ git clone https://github.com/iam4x/zsh-iterm-touchbar.git`

Then add the plugin into your `~/.zshr`:

```
plugins=(... zsh-iterm-touchbar)
```

**Comment by jtmkrueger** [comment]
no, that didn't seem to do anything. It's still doesn't seem to be doing anything. Just to be clear, I'm using the iterm nightlies, so I don't think the compatibility issue is coming from there. I don't know if the `pre_cmd()` function is ever firing (maybe?)

**Comment by iam4x** [comment]
@jtmkrueger Can you try to rename `pre_cmd()` to `precmd()`?

**Comment by jtmkrueger** [comment]
ah, that seemed to start to do something:
```
precmd:23: command not found: spaceship_git_uncomitted
precmd:24: command not found: spaceship_git_unstaged
precmd:25: command not found: spaceship_git_untracked
precmd:26: command not found: spaceship_git_stashed
precmd:27: command not found: spaceship_git_unpushed_unpulled
```

showed up at the top of a new shell tab!

**Comment by iam4x** [comment]
Thank's will push a fix 👍

**Comment by iam4x** [comment]
Should be fixed on master, can you try again and give me result @jtmkrueger ?

**Comment by jtmkrueger** [comment]
looks like that did the trick!
