### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by criswell** [iam4x/zsh-iterm-touchbar#18]
I don't see a license specification the repo.

Because there's no specified license, there's an implicit copyright on the code.

See: https://blog.codinghorror.com/pick-a-license-any-license/

I'd like to fork and add some vim specific things I'd like to have (and maybe issue a PR, if you're interested in them as well), but absent any license, that's perilous.

Another good resource: https://choosealicense.com/

**Comment by sandrodz** [comment]
vim specific things would be awesome.

**Comment by iam4x** [comment]
Thanks for the reminder :)
