### ISSUE TITLE
'node' missing from requirements

### ISSUE THREAD

**Issue by Stealthii** [iam4x/zsh-iterm-touchbar#22]
The requirements section of the Readme doesn't mention `node` as a requirement in order to use some features of this plugin (and doesn't gracefully downgrade when it's not available).

Adding this to the requirements, or disabling branch searching/switching, etc. when it's not available on PATH would be ideal.

No PR submitted as not sure on which approach is preferred.

**Comment by iam4x** [comment]
Fixed with #28
