### ISSUE TITLE
This plugin is trying to acces my mail data

### ISSUE THREAD

**Issue by ghost** [iam4x/zsh-iterm-touchbar#34]
I got this when I added the plugin to my ~/.zshrc:

" Directory 'Library/Containers/com.apple.mail/Data/DataVaults/': Operation not permitted "

**Comment by iam4x** [comment]
Hi @sasokess 

You can read the code source of the plugin here: https://github.com/iam4x/zsh-iterm-touchbar/blob/master/zsh-iterm-touchbar.plugin.zsh there's nothing relating to emails or trying to get user data.

What are the other plugins in your .zshrc?
