### ISSUE TITLE
tmux support

### ISSUE THREAD

**Issue by amdprophet** [iam4x/zsh-iterm-touchbar#9]
These features don't seem to work when in a tmux session. Is this a limitation of iTerm2 or is there some way support can be added to this project?

**Comment by iam4x** [comment]
Hello @amdprophet I have no knowledge about tmux. I think it's feasable since I made a Exit+Save button for vim that way:

```
~/.vimrc

autocmd VimEnter * silent !echo -ne "\033]1337;PopKeyLabels\a"
autocmd VimEnter * silent !echo -ne "\033]1337;SetKeyLabel=F1=Save & Quit\a"
autocmd VimEnter * map <F1> :wq<CR>
autocmd VimEnter * silent !echo -ne "\033]1337;SetKeyLabel=F2=Quit\a"
autocmd VimEnter * map <F2> :q!<CR>
```

Does that can help you?

**Comment by TheRockyOng** [comment]
tmux apparently absorbs all those escape sequence. Not sure what the best way to make it bypasses tmux

**Comment by iam4x** [comment]
Merged 👍

**Comment by sandrodz** [comment]
It doesn't work for me in tmux. I'm inside a box via ssh that has tmux, could that be a problem?

**Comment by seajaysec** [comment]
Not working for me in local tmux.
